name: widgets_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.4.1
  flutter_code_editor: ^0.3.2
  highlight: ^0.7.0
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
